<?php

/**
 * ConstantContact template
 * 
 * @category    Aydus
 * @package     Aydus_ConstantContact
 * @author      Aydus <davidt@aydus.com>
 */
?>
<div id="constantcontact">
    <div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>
    
    <div class="page-title">
        <h1>Subscribe</h1>
    </div>
    
    <form name="subscribe-form" id="subscribeForm" action="<?php echo $this->getFormAction() ?>" method="post" class="">
        <?php echo $this->getBlockHtml('formkey') ?>
        <div class="fieldset">
            <ul class="form-list">
                <li>
                    <label for="list" class="required"><em>*</em><?php echo $this->__('Select List') ?></label>
                    <div class="input-box">
                        <select name="list" class="required-entry" >
                            <option value="">-- Select List --</option>
                        <?php foreach ($this->getLists() as $list) : ?>
                            <option value="<?php echo $list->id; ?>"><?php echo $list->name; ?></option>
                        <?php endforeach; ?>
                        </select>
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="prefix"><?php echo Mage::helper('aydus_constantcontact')->__('Prefix') ?></label>
                        <div class="input-box">
                            <input name="prefix" id="prefix" title="<?php echo Mage::helper('aydus_constantcontact')->__('Prefix') ?>" value="<?php echo $this->escapeHtml($this->getCustomer()->getPrefix()) ?>" class="input-text" type="text" />
                        </div>
                    </div>                
                    <div class="field">
                        <label for="firstname" class="required"><em>*</em><?php echo Mage::helper('aydus_constantcontact')->__('First Name') ?></label>
                        <div class="input-box">
                            <input name="firstname" id="firstname" title="<?php echo Mage::helper('aydus_constantcontact')->__('First Name') ?>" value="<?php echo $this->escapeHtml($this->getCustomer()->getFirstname()) ?>" class="input-text required-entry" type="text" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="middlename"><?php echo Mage::helper('aydus_constantcontact')->__('Middle Name') ?></label>
                        <div class="input-box">
                            <input name="middlename" id="middlename" title="<?php echo Mage::helper('aydus_constantcontact')->__('Middle Name') ?>" value="<?php echo $this->escapeHtml($this->getCustomer()->getMiddlename()) ?>" class="input-text" type="text" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="lastname" class="required"><em>*</em><?php echo Mage::helper('aydus_constantcontact')->__('Last Name') ?></label>
                        <div class="input-box">
                            <input name="lastname" id="lastname" title="<?php echo Mage::helper('aydus_constantcontact')->__('Last Name') ?>" value="<?php echo $this->escapeHtml($this->getCustomer()->getLastname()) ?>" class="input-text required-entry" type="text" />
                        </div>
                    </div>
                </li>
                <li>
                    <label for="email" class="required"><em>*</em><?php echo Mage::helper('aydus_constantcontact')->__('Email') ?></label>
                    <div class="input-box">
                        <input name="email" id="email" title="<?php echo Mage::helper('aydus_constantcontact')->__('Email') ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="text" />
                    </div>
                </li>
                <li>
                    <label for="telephone"><?php echo Mage::helper('aydus_constantcontact')->__('Telephone') ?></label>
                    <div class="input-box">
                        <input name="telephone" id="telephone" title="<?php echo Mage::helper('aydus_constantcontact')->__('Telephone') ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" class="input-text" type="text" />
                    </div>
                </li>
                <li>
                    <label for="company"><?php echo Mage::helper('aydus_constantcontact')->__('Company') ?></label>
                    <div class="input-box">
                        <input name="company" id="company" title="<?php echo Mage::helper('aydus_constantcontact')->__('Company') ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" class="input-text" type="text" />
                    </div>
                </li>
                <li>
                    <label for="street"><?php echo Mage::helper('aydus_constantcontact')->__('Address') ?></label>
                    <div class="input-box">
                        <?php $streets = $this->getAddress()->getStreet(); ?>
                        <?php $street = $streets[0]; ?>
                        <input name="street[0]" id="street-0" title="<?php echo Mage::helper('aydus_constantcontact')->__('Address') ?>" value="<?php echo $this->escapeHtml($street) ?>" class="input-text" type="text" />
                    </div>
                    <div class="input-box">
                        <?php $street2 = $streets[1]; ?>
                        <input name="street[1]" id="street-1" title="<?php echo Mage::helper('aydus_constantcontact')->__('Address Line 2') ?>" value="<?php echo $this->escapeHtml($street2) ?>" class="input-text" type="text" />
                    </div>
                </li>   
                <li>
                    <label for="city"><?php echo Mage::helper('aydus_constantcontact')->__('City') ?></label>
                    <div class="input-box">
                        <input name="city" id="city" title="<?php echo Mage::helper('aydus_constantcontact')->__('City') ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text" type="text" />
                    </div>
                </li>    
                <li>
                    <label for="region"><?php echo Mage::helper('aydus_constantcontact')->__('Region') ?></label>
                    <div class="input-box">
                        <input name="region" id="region" title="<?php echo Mage::helper('aydus_constantcontact')->__('Region') ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>" class="input-text" type="text" />
                    </div>
                </li>                                            
                <li>
                    <label for="region_id"><?php echo Mage::helper('aydus_constantcontact')->__('State/Region') ?></label>
                    <div class="input-box">
                        <select name="region_id">
                            <?php foreach ($this->getRegions() as $region):?>
                            <option value="<?php echo $region['value']?>" <?php if ($region['value'] == $this->getAddress()->getRegionId()):?>selected="selected"<?php endif;?>><?php echo $region['label']?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </li>         
                <li>
                    <label for="country_id"><?php echo Mage::helper('aydus_constantcontact')->__('Country') ?></label>
                    <div class="input-box">
                        <select name="country_id">
                            <?php foreach ($this->getCountries() as $country):?>
                            <option value="<?php echo $country['value']?>" <?php if ($country['value'] == $this->getAddress()->getCountryId()):?>selected="selected"<?php endif;?>><?php echo $country['label']?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </li>                                             
                <li>
                    <label for="postcode"><?php echo Mage::helper('aydus_constantcontact')->__('Zip/Postcode') ?></label>
                    <div class="input-box">
                        <input name="postcode" id="postcode" title="<?php echo Mage::helper('aydus_constantcontact')->__('Zip/Postcode') ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input-text" type="text" />
                    </div>
                </li>                  
            </ul>
        </div>
        <div class="buttons-set">
            <p class="required"><?php echo Mage::helper('aydus_constantcontact')->__('* Required Fields') ?></p>
            <button type="submit" title="<?php echo Mage::helper('aydus_constantcontact')->__('Submit') ?>" class="button"><span><span><?php echo Mage::helper('contacts')->__('Submit') ?></span></span></button>
        </div>        
    </form>
    
</div>

<script type="text/javascript">
//<![CDATA[
    var subscribeForm = new VarienForm('subscribeForm', true);
//]]>
</script>